### ISSUE TITLE
Object #<Push> has no method 'parse'

### ISSUE THREAD

**Issue by GabLeRoux** [andrewtarry/hubot-bitbucket#2]
Hey there, me again, Seems like my change for #1 fixed the issue I was getting, but I quickly tested again and here's what I'm getting, not sure if I'm doing something wrong.

```
TypeError: Object #<Push> has no method 'parse'
 at /app/node_modules/hubot-bitbucket/src/push-hook.coffee:27:5, <js>:11:19
 at callbacks (/app/node_modules/hubot/node_modules/express/lib/router/index.js:164:37)
 at param (/app/node_modules/hubot/node_modules/express/lib/router/index.js:138:11)
 at pass (/app/node_modules/hubot/node_modules/express/lib/router/index.js:145:5)
 at Router._dispatch (/app/node_modules/hubot/node_modules/express/lib/router/index.js:173:5)
 at Object.router (/app/node_modules/hubot/node_modules/express/lib/router/index.js:33:10)
 at next (/app/node_modules/hubot/node_modules/express/node_modules/connect/lib/proto.js:169:15)
 at Object.multipart [as handle] (/app/node_modules/hubot/node_modules/connect-multiparty/index.js:42:27)
 at next (/app/node_modules/hubot/node_modules/express/node_modules/connect/lib/proto.js:169:15)
 at Object.urlencodedParser [as handle] (/app/node_modules/hubot/node_modules/express/node_modules/connect/node_modules/body-parser/lib/types/urlencoded.js:69:27)
 at next (/app/node_modules/hubot/node_modules/express/node_modules/connect/lib/proto.js:169:15)
 at /app/node_modules/hubot/node_modules/express/node_modules/connect/node_modules/body-parser/lib/read.js:107:5
 at IncomingMessage.onEnd (/app/node_modules/hubot/node_modules/express/node_modules/connect/node_modules/body-parser/node_modules/raw-body/index.js:136:7)
 at IncomingMessage.g (events.js:180:16)
 at IncomingMessage.emit (events.js:92:17)
 at _stream_readable.js:944:16
 at process._tickCallback (node.js:448:13)
```

I managed to test locally by cloning `hubot-bitbucket` into scripts folder, ran `npm install` inside. For some reason, `hubot-bitbucket` didn't seem to load even with `hubot-bitbucket` being added to `hubot-scripts.json`, but I it's being loaded wen using `./node_modules/hubot/bin/hubot -r ./scripts/hubot-bitbucket`. Anyway, this time, posting manually to `http://localhost:8080/bitbucket/push` with [postman]() using bitbucket's post example

```
{
    "canon_url": "https://bitbucket.org",
    "commits": [
        {
            "author": "marcus",
            "branch": "master",
            "files": [
                {
                    "file": "somefile.py",
                    "type": "modified"
                }
            ],
            "message": "Added some more things to somefile.py\n",
            "node": "620ade18607a",
            "parents": [
                "702c70160afc"
            ],
            "raw_author": "Marcus Bertrand <marcus@somedomain.com>",
            "raw_node": "620ade18607ac42d872b568bb92acaa9a28620e9",
            "revision": null,
            "size": -1,
            "timestamp": "2012-05-30 05:58:56",
            "utctimestamp": "2012-05-30 03:58:56+00:00"
        }
    ],
    "repository": {
        "absolute_url": "/marcus/project-x/",
        "fork": false,
        "is_private": true,
        "name": "Project X",
        "owner": "marcus",
        "scm": "git",
        "slug": "project-x",
        "website": "https://atlassian.com/"
    },
    "user": "marcus"
}
```

I get this:

```
TypeError: undefined is not a function
 at /hubot/scripts/hubot-bitbucket/src/push-hook.coffee:27:17
 at callbacks (/hubot/node_modules/hubot/node_modules/express/lib/router/index.js:164:37)
 at param (/hubot/node_modules/hubot/node_modules/express/lib/router/index.js:138:11)
 at pass (/hubot/node_modules/hubot/node_modules/express/lib/router/index.js:145:5)
 at Router._dispatch (/hubot/node_modules/hubot/node_modules/express/lib/router/index.js:173:5)
 at Object.router (/hubot/node_modules/hubot/node_modules/express/lib/router/index.js:33:10)
 at next (/hubot/node_modules/hubot/node_modules/express/node_modules/connect/lib/proto.js:169:15)
 at Object.multipart [as handle] (/hubot/node_modules/hubot/node_modules/connect-multiparty/index.js:42:27)
 at next (/hubot/node_modules/hubot/node_modules/express/node_modules/connect/lib/proto.js:169:15)
 at Object.urlencodedParser [as handle] (/hubot/node_modules/hubot/node_modules/express/node_modules/connect/node_modules/body-parser/lib/types/urlencoded.js:69:27)
 at next (/hubot/node_modules/hubot/node_modules/express/node_modules/connect/lib/proto.js:169:15)
 at /hubot/node_modules/hubot/node_modules/express/node_modules/connect/node_modules/body-parser/lib/read.js:107:5
 at IncomingMessage.onEnd (/hubot/node_modules/hubot/node_modules/express/node_modules/connect/node_modules/body-parser/node_modules/raw-body/index.js:136:7)
 at IncomingMessage.g (events.js:199:16)
 at IncomingMessage.emit (events.js:104:17)
 at _stream_readable.js:908:16
 at process._tickCallback (node.js:355:11)
```

I've noticed that when running locally, I also see this warning on start:

```
WARNING Expected /hubot/scripts/hubot-bitbucket/package to assign a function to module.exports, got object
```

**Comment by GabLeRoux** [comment]
This is quite easy to fix:

``` coffeescript
Push = require '../lib/Push'

module.exports = (robot) ->
  bitbucketPushUrl = process.env.HUBOT_BITBUCKET_PUSH_URL or '/bitbucket/push'
  bitbucketPushEvent = process.env.HUBOT_BITBUCKET_PUSH_EVENT or 'bitbucketPushReceived'

  # Listen for bitbucket sending a commit
  #
  # The push listener will only parse the body and emit an event to be picked
  # up elsewhere
  robot.router.post bitbucketPushUrl, (req, res) ->
    push = Push.parse req.body

    robot.emit bitbucketPushEvent,
      "push": push

    res.send 'OK'
```

Actual json in `req.body`:

``` coffeescript
   { canon_url: 'https://bitbucket.org',
     commits: [ [Object] ],
     repository:
      { absolute_url: '/marcus/project-x/',
        fork: false,
        is_private: true,
        name: 'Project X',
        owner: 'marcus',
        scm: 'git',
        slug: 'project-x',
        website: 'https://atlassian.com/' },
     user: 'marcus' }
```

`Push` object:

``` coffeescript
   { repo:
      { url: 'https://bitbucket.org/marcus/project-x/',
        name: 'Project X',
        slug: 'project-x' },
     commits: [ [Object] ] }
```

Turns out the `Push` object is missing some data, so I'm using `robot.emit bitbucketPushEvent, req.body` instead.
